language: java

git:
  depth: 10

matrix:
  include:
    - os: linux
      dist: trusty
      env: 
        - ZIPPY_JDK_TYPE=STANDARD_LINUX
        - IS_GRAALJVM=FASLE
      jdk: openjdk8
      addons:
        apt:
          packages:
            - oracle-java8-installer
    - os: linux
      dist: trusty
      sudo: required
      env: 
        - ZIPPY_JDK_TYPE=GRAALJVM_LINUX
        - IS_GRAALJVM=TRUE
      jdk: openjdk8
      addons:
        apt:
          packages:
            - oracle-java8-installer
    - os: osx
      env: 
        - ZIPPY_JDK_TYPE=STANDARD_OSX
        - IS_GRAALJVM=FASLE
      osx_image: xcode8.2
    - os: osx
      env: 
        - ZIPPY_JDK_TYPE=GRAALJVM_OSX
        - IS_GRAALJVM=TRUE
      osx_image: xcode8.2

before_install:
  - echo $TRAVIS_OS_NAME
  - java -version
  - hg --version
  - python --version
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
        brew update;
        brew tap caskroom/cask;
        brew cask reinstall java;
        ls -l /Library/Java/JavaVirtualMachines/;
        export JAVA_HOME=$(/usr/libexec/java_home); 
    fi
  - echo $JAVA_HOME

script:
  - echo $JAVA_HOME

after_success:
  - echo "SUCCESSFUL build and test :)"

after_failure:
  - echo "FAILURE build and/or test :("
