matrix:
  global:
    - JVMCI_VERSION="jvmci-0.36"
    - JVMCI_BASE_JDK8="openjdk1.8.0_141"
  include:
    - os: linux
      # sudo will force Travis-CI to build on a machine that has larger memory (required for building JVMCI)
      sudo: required
      dist: trusty
      env:
        - ZIPPY_JDK_TYPE=GRAALJVM_LINUX
        - BUILD_JVMCI=FALSE
        - IS_GRAALJVM=TRUE
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - oracle-java8-installer
            - wget
    - os: osx
      env:
        - ZIPPY_JDK_TYPE=GRAALJVM_OSX
        - BUILD_JVMCI=TRUE
        - IS_GRAALJVM=TRUE
      osx_image: xcode8.2

before_install:
  - echo $TRAVIS_OS_NAME
  - java -version
  - hg --version
  - python --version
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update;
        brew tap caskroom/cask;
        brew cask reinstall java;
        ls -l /Library/Java/JavaVirtualMachines/;
        export JAVA_HOME=$(/usr/libexec/java_home);
    fi
  - echo $JAVA_HOME
  - export DEFAULT_VM=server
  - git clone https://github.com/graalvm/mx.git ../mx
  - export PATH=$PWD/../mx:$PATH

install:
  - if [ "$IS_GRAALJVM" == "TRUE" ]; then
        if [ "$BUILD_JVMCI" == "FALSE" ]; then
          JDK_TAR=${TRAVIS_BUILD_DIR}/../jdk.tar.gz;
          wget https://github.com/dougxc/openjdk8-jvmci-builder/releases/download/${JVMCI_VERSION}/${JVMCI_BASE_JDK8}-${JVMCI_VERSION}-linux-amd64.tar.gz -O ${JDK_TAR};
          tar -C ${TRAVIS_BUILD_DIR}/.. -xzf ${JDK_TAR};
          export JAVA_HOME=${TRAVIS_BUILD_DIR}/../${JVMCI_BASE_JDK8}-${JVMCI_VERSION};
        else
          cd ..;
          hg clone http://hg.openjdk.java.net/graal/graal-jvmci-8;
          cd graal-jvmci-8;
          hg update ${JVMCI_VERSION};
          mx build;
          export JAVA_HOME=$(mx jdkhome);
        fi

        echo $JAVA_HOME;
        mx jdkhome;
        cd ../zippy;
        export DEFAULT_DYNAMIC_IMPORTS=truffle/compiler;
        export ZIPPY_MUST_USE_GRAAL=1;
    fi
